version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: indexer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  unruggableMemecoin-deploy-indexer:
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    image: quay.io/apibara/sink-postgres:latest
    command: 'run ./indexer/unruggableMemecoin-deploy.indexer.ts --connection-string postgresql://admin:password@postgres:5432/indexer -A ${AUTH_TOKEN}'
    volumes:
      - ./src:/indexer
    depends_on:
      - postgres
    networks:
      - backend
    restart: on-failure

  unruggableMemecoin-launch-indexer:
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    image: quay.io/apibara/sink-postgres:latest
    command: 'run ./indexer/unruggableMemecoin-launch.indexer.ts --connection-string postgresql://admin:password@postgres:5432/indexer -A ${AUTH_TOKEN}'
    volumes:
      - ./src:/indexer
    depends_on:
      - postgres
    networks:
      - backend
    restart: on-failure

  unruggableMemecoin-transfers-indexer:
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    image: quay.io/apibara/sink-postgres:latest
    command: 'run ./indexer/unruggableMemecoin-transfers.indexer.ts --connection-string postgresql://admin:password@postgres:5432/indexer -A ${AUTH_TOKEN}'
    volumes:
      - ./src:/indexer
    depends_on:
      - postgres
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    driver: bridge
